## Label Scenario 3

In [1]:
#
# Cell 1: Libraries laden
#

import pandas as pd
import numpy as np
import wfdb
import ast

In [3]:
#
# Cell 2:Path for input data and definition of sampling rate
#

#path = 'C:/Users/Buchh/OneDrive/Leuphana_Data_Science/Masterarbeit/ECG/Python/Daten_einlesen/test_data/'
path = 'E:/MA_Daten_2/ptb-xl-a-large-publicly-available-electrocardiography-dataset-1.0.3/'
sampling_rate=100

In [5]:
#
# Cell 3: Definition of functions
#

def load_raw_data(df, sampling_rate, path):
    if sampling_rate == 100:
        data = [wfdb.rdsamp(path+f) for f in df.filename_lr]
    else:
        data = [wfdb.rdsamp(path+f) for f in df.filename_hr]
    data = np.array([signal for signal, meta in data])
    return data

def aggregate_diagnostic(y_dic):
    tmp = []
    for key in y_dic.keys():
        if key in agg_df.index:
            tmp.append(agg_df.loc[key].diagnostic_class)
    return list(set(tmp))

def aggregate_form_rhythm(y_dic): #BuK
    tmp = []
    for key in y_dic.keys():
        if key in agg_df.index:
            tmp.append(agg_df.loc[key].form_rhythm)
    return list(set(tmp))

def aggregate_form(y_dic): #BuK
    tmp = []
    for key in y_dic.keys():
        if key in agg_df_form.index:
            tmp.append(agg_df.loc[key].form)
    return list(set(tmp))

In [7]:
#
# Cell 3a: Specify the directory name for loading of data
#

from pathlib import Path

directory_path = Path("D:/ECG/X_zero")

In [9]:
#
# Cell 4:Loading stored raw data, if available. 
#

#X = np.load('X_np_array.npy')
Y = pd.read_pickle(directory_path/'Y_data.pkl')

In [11]:
#
# Cell 5: FORM LABELS and RHYTHM Labels
# Load scp_statements.csv for form and rhythm aggregation (BuK)
#

agg_df = pd.read_csv(path+'scp_statements.csv', index_col=0)
agg_df = agg_df[(agg_df.form == 1) | (agg_df.rhythm == 1)]
#agg_df = agg_df[(agg_df.form == 1)]
agg_df['form_rhythm'] = agg_df.index
#agg_df['form'] = agg_df.index

#agg_df

In [13]:
#
# Cell 6: FORM LABELS
# Load scp_statements.csv for form and rhythm aggregation (BuK)
#

agg_df_form = pd.read_csv(path+'scp_statements.csv', index_col=0)
#agg_df = agg_df[(agg_df.form == 1) | (agg_df.rhythm == 1)]
agg_df_form = agg_df_form[(agg_df_form.form == 1)]
#agg_df['form_rhythm'] = agg_df.index
agg_df_form['form'] = agg_df_form.index

#agg_df_form

In [15]:
#
# Cell 7: RHYTHM LABELS
# Load scp_statements.csv for hythm aggregation (BuK)
#

agg_df_rhythm = pd.read_csv(path+'scp_statements.csv', index_col=0)
#agg_df = agg_df[(agg_df.form == 1) | (agg_df.rhythm == 1)]
agg_df_rhythm = agg_df_rhythm[(agg_df_rhythm.rhythm == 1)]
#agg_df['form_rhythm'] = agg_df.index
agg_df_rhythm['rhythm'] = agg_df_rhythm.index

# agg_df_rhythm

In [17]:
#
#Cell 8: Apply form and rhythm class, BuK
#

Y['label'] = Y.scp_codes.apply(aggregate_form_rhythm)
#Y['label'] = Y.scp_codes.apply(aggregate_form)
display(Y)

,ecg_id,patient_id,age,sex,height,weight,nurse,site,device,recording_date,...,baseline_drift,static_noise,burst_noise,electrodes_problems,extra_beats,pacemaker,strat_fold,filename_lr,filename_hr,label
0,1,15709.0,56.0,1,NaN,63.0,2.0,0.0,CS-12 E,1984-11-09 09:17:34,...,NaN,", I-V1,",NaN,NaN,NaN,NaN,3,records100/00000/00001_lr,records500/00000/00001_hr,"[SR, LVOLT]"
1,2,13243.0,19.0,0,NaN,70.0,2.0,0.0,CS-12 E,1984-11-14 12:55:37,...,NaN,NaN,NaN,NaN,NaN,NaN,2,records100/00000/00002_lr,records500/00000/00002_hr,[SBRAD]
2,3,20372.0,37.0,1,NaN,69.0,2.0,0.0,CS-12 E,1984-11-15 12:49:10,...,NaN,NaN,NaN,NaN,NaN,NaN,5,records100/00000/00003_lr,records500/00000/00003_hr,[SR]
3,4,17014.0,24.0,0,NaN,82.0,2.0,0.0,CS-12 E,1984-11-15 13:44:57,...,", II,III,AVF",NaN,NaN,NaN,NaN,NaN,3,records100/00000/00004_lr,records500/00000/00004_hr,[SR]
4,5,17448.0,19.0,1,NaN,70.0,2.0,0.0,CS-12 E,1984-11-17 10:43:15,...,", III,AVR,AVF",NaN,NaN,NaN,NaN,NaN,4,records100/00000/00005_lr,records500/00000/00005_hr,[SR]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21794,21833,17180.0,67.0,1,NaN,NaN,1.0,2.0,AT-60 3,2001-05-31 09:14:35,...,NaN,", alles,",NaN,NaN,1ES,NaN,7,records100/21000/21833_lr,records500/21000/21833_hr,"[STACH, VCLVH, NDT, PVC]"
21795,21834,20703.0,300.0,0,NaN,NaN,1.0,2.0,AT-60 3,2001-06-05 11:33:39,...,NaN,NaN,NaN,NaN,NaN,NaN,4,records100/21000/21834_lr,records500/21000/21834_hr,"[SR, ABQRS]"
21796,21835,19311.0,59.0,1,NaN,NaN,1.0,2.0,AT-60 3,2001-06-08 10:30:27,...,NaN,", I-AVR,",NaN,NaN,NaN,NaN,2,records100/21000/21835_lr,records500/21000/21835_hr,[SR]
21797,21836,8873.0,64.0,1,NaN,NaN,1.0,2.0,AT-60 3,2001-06-09 18:21:49,...,NaN,NaN,NaN,NaN,SVES,NaN,8,records100/21000/21836_lr,records500/21000/21836_hr,[SR]
21798,21837,11744.0,68.0,0,NaN,NaN,1.0,2.0,AT-60 3,2001-06-11 16:43:01,...,NaN,", I-AVL,",NaN,NaN,NaN,NaN,9,records100/21000/21837_lr,records500/21000/21837_hr,[SR]

In [19]:
#
#Cell 9: Make a copy from Y for further manipulation
#

Y_copy = Y[['ecg_id','patient_id','strat_fold','scp_codes','label']].copy() 
Y_copy

,ecg_id,patient_id,strat_fold,scp_codes,label
0,1,15709.0,3,"{'NORM': 100.0, 'LVOLT': 0.0, 'SR': 0.0}","[SR, LVOLT]"
1,2,13243.0,2,"{'NORM': 80.0, 'SBRAD': 0.0}",[SBRAD]
2,3,20372.0,5,"{'NORM': 100.0, 'SR': 0.0}",[SR]
3,4,17014.0,3,"{'NORM': 100.0, 'SR': 0.0}",[SR]
4,5,17448.0,4,"{'NORM': 100.0, 'SR': 0.0}",[SR]
...,...,...,...,...,...
21794,21833,17180.0,7,"{'NDT': 100.0, 'PVC': 100.0, 'VCLVH': 0.0, 'ST...","[STACH, VCLVH, NDT, PVC]"
21795,21834,20703.0,4,"{'NORM': 100.0, 'ABQRS': 0.0, 'SR': 0.0}","[SR, ABQRS]"
21796,21835,19311.0,2,"{'ISCAS': 50.0, 'SR': 0.0}",[SR]
21797,21836,8873.0,8,"{'NORM': 100.0, 'SR': 0.0}",[SR]
21798,21837,11744.0,9,"{'NORM': 100.0, 'SR': 0.0}",[SR]

## Y-data manipulation for augmentation starts

In [27]:
#
# Cell 9a: 
#

from pathlib import Path
directory_path_augm = Path("d:/ECG/X_augmented")

In [29]:
#
# Cell 9b: loads dicitionary with augmented X-xata
#

import pickle

with open(directory_path_augm/'X_augmented_accomp.pkl', 'rb') as f:
    X_augmented_accomp = pickle.load(f) # deserialize using load()
f.close()  

X_augmented_accomp

{'# of additional X-Data concatenated': 2}

In [31]:
#
# Cell 9c: select a certain row for later control purposes:
#

Y_21712 = Y_copy[Y_copy.index==21712].copy()
Y_21712

       ecg_id  patient_id  strat_fold                   scp_codes label
21712   21751     10487.0           3  {'NORM': 100.0, 'SR': 0.0}  [SR]

In [33]:
#
# Cell 9d: concatenates the df Y_copy according to the value of  
# '# of additional X-Data concatenated':
#

Y_add=Y_copy
for i in range(0, X_augmented_accomp.get('# of additional X-Data concatenated')):
    Y_copy= pd.concat([Y_copy,Y_add], axis=0, ignore_index= True).copy()

Y_copy

,ecg_id,patient_id,strat_fold,scp_codes,label
0,1,15709.0,3,"{'NORM': 100.0, 'LVOLT': 0.0, 'SR': 0.0}","[SR, LVOLT]"
1,2,13243.0,2,"{'NORM': 80.0, 'SBRAD': 0.0}",[SBRAD]
2,3,20372.0,5,"{'NORM': 100.0, 'SR': 0.0}",[SR]
3,4,17014.0,3,"{'NORM': 100.0, 'SR': 0.0}",[SR]
4,5,17448.0,4,"{'NORM': 100.0, 'SR': 0.0}",[SR]
...,...,...,...,...,...
65392,21833,17180.0,7,"{'NDT': 100.0, 'PVC': 100.0, 'VCLVH': 0.0, 'ST...","[NDT, STACH, PVC, VCLVH]"
65393,21834,20703.0,4,"{'NORM': 100.0, 'ABQRS': 0.0, 'SR': 0.0}","[SR, ABQRS]"
65394,21835,19311.0,2,"{'ISCAS': 50.0, 'SR': 0.0}",[SR]
65395,21836,8873.0,8,"{'NORM': 100.0, 'SR': 0.0}",[SR]
65396,21837,11744.0,9,"{'NORM': 100.0, 'SR': 0.0}",[SR]

In [35]:
#
# Cell 7e: compare two df extracts for control of correct index assignment  
# 21712 + 21799 = 43511
#

Y_43511 = Y_copy[Y_copy.index==43511].copy()
display(Y_43511)
display(Y_21712)

       ecg_id  patient_id  strat_fold                   scp_codes label
43511   21751     10487.0           3  {'NORM': 100.0, 'SR': 0.0}  [SR]

       ecg_id  patient_id  strat_fold                   scp_codes label
21712   21751     10487.0           3  {'NORM': 100.0, 'SR': 0.0}  [SR]

In [37]:
Y_65310 = Y_copy[Y_copy.index==65310].copy()
display(Y_65310)

       ecg_id  patient_id  strat_fold                   scp_codes label
65310   21751     10487.0           3  {'NORM': 100.0, 'SR': 0.0}  [SR]

## Y-data manipulation for augmentation ends
## The remaining cells are indentical with the cells of the modul for not augmented data

In [23]:
#Cell 9a: information

#control = ['SR']

#Y_copy[Y_copy.label.isin(control)]

In [21]:
#
# Cell 10: in all combinations of labels with "SR" remove "SR" 
# clean list of labels is now stored in the column "codes"
#

Y_copy["codes"] = Y_copy["label"].apply(
    lambda lst: ["SR"] if len(lst) == 1 and lst[0] == "SR"
    else sorted([c for c in lst if c != "SR"])
)
Y_copy

,ecg_id,patient_id,strat_fold,scp_codes,label,codes
0,1,15709.0,3,"{'NORM': 100.0, 'LVOLT': 0.0, 'SR': 0.0}","[SR, LVOLT]",[LVOLT]
1,2,13243.0,2,"{'NORM': 80.0, 'SBRAD': 0.0}",[SBRAD],[SBRAD]
2,3,20372.0,5,"{'NORM': 100.0, 'SR': 0.0}",[SR],[SR]
3,4,17014.0,3,"{'NORM': 100.0, 'SR': 0.0}",[SR],[SR]
4,5,17448.0,4,"{'NORM': 100.0, 'SR': 0.0}",[SR],[SR]
...,...,...,...,...,...,...
21794,21833,17180.0,7,"{'NDT': 100.0, 'PVC': 100.0, 'VCLVH': 0.0, 'ST...","[STACH, VCLVH, NDT, PVC]","[NDT, PVC, STACH, VCLVH]"
21795,21834,20703.0,4,"{'NORM': 100.0, 'ABQRS': 0.0, 'SR': 0.0}","[SR, ABQRS]",[ABQRS]
21796,21835,19311.0,2,"{'ISCAS': 50.0, 'SR': 0.0}",[SR],[SR]
21797,21836,8873.0,8,"{'NORM': 100.0, 'SR': 0.0}",[SR],[SR]
21798,21837,11744.0,9,"{'NORM': 100.0, 'SR': 0.0}",[SR],[SR]

In [23]:
#
#Cell 11: determines length of lists "codes" and add the sesult to the column "len"
#

Y_copy["len"] = Y_copy["codes"].apply(
    lambda lst: len(lst)
)
Y_copy

,ecg_id,patient_id,strat_fold,scp_codes,label,codes,len
0,1,15709.0,3,"{'NORM': 100.0, 'LVOLT': 0.0, 'SR': 0.0}","[SR, LVOLT]",[LVOLT],1
1,2,13243.0,2,"{'NORM': 80.0, 'SBRAD': 0.0}",[SBRAD],[SBRAD],1
2,3,20372.0,5,"{'NORM': 100.0, 'SR': 0.0}",[SR],[SR],1
3,4,17014.0,3,"{'NORM': 100.0, 'SR': 0.0}",[SR],[SR],1
4,5,17448.0,4,"{'NORM': 100.0, 'SR': 0.0}",[SR],[SR],1
...,...,...,...,...,...,...,...
21794,21833,17180.0,7,"{'NDT': 100.0, 'PVC': 100.0, 'VCLVH': 0.0, 'ST...","[STACH, VCLVH, NDT, PVC]","[NDT, PVC, STACH, VCLVH]",4
21795,21834,20703.0,4,"{'NORM': 100.0, 'ABQRS': 0.0, 'SR': 0.0}","[SR, ABQRS]",[ABQRS],1
21796,21835,19311.0,2,"{'ISCAS': 50.0, 'SR': 0.0}",[SR],[SR],1
21797,21836,8873.0,8,"{'NORM': 100.0, 'SR': 0.0}",[SR],[SR],1
21798,21837,11744.0,9,"{'NORM': 100.0, 'SR': 0.0}",[SR],[SR],1

In [25]:
#
# Cell 12: filters all instances with length zero (only for control purposes) 
# Note: these instances are ECGs with neither form nor rhythm statments but tagged with a diagnostic label.
# Very few instance are labelled with "NORM". These ECGs could have been added to the SR class but this ...  
#

Y_copy = Y_copy[Y_copy["len"]>0].copy()
Y_copy

,ecg_id,patient_id,strat_fold,scp_codes,label,codes,len
0,1,15709.0,3,"{'NORM': 100.0, 'LVOLT': 0.0, 'SR': 0.0}","[SR, LVOLT]",[LVOLT],1
1,2,13243.0,2,"{'NORM': 80.0, 'SBRAD': 0.0}",[SBRAD],[SBRAD],1
2,3,20372.0,5,"{'NORM': 100.0, 'SR': 0.0}",[SR],[SR],1
3,4,17014.0,3,"{'NORM': 100.0, 'SR': 0.0}",[SR],[SR],1
4,5,17448.0,4,"{'NORM': 100.0, 'SR': 0.0}",[SR],[SR],1
...,...,...,...,...,...,...,...
21794,21833,17180.0,7,"{'NDT': 100.0, 'PVC': 100.0, 'VCLVH': 0.0, 'ST...","[STACH, VCLVH, NDT, PVC]","[NDT, PVC, STACH, VCLVH]",4
21795,21834,20703.0,4,"{'NORM': 100.0, 'ABQRS': 0.0, 'SR': 0.0}","[SR, ABQRS]",[ABQRS],1
21796,21835,19311.0,2,"{'ISCAS': 50.0, 'SR': 0.0}",[SR],[SR],1
21797,21836,8873.0,8,"{'NORM': 100.0, 'SR': 0.0}",[SR],[SR],1
21798,21837,11744.0,9,"{'NORM': 100.0, 'SR': 0.0}",[SR],[SR],1

In [27]:
#
# Cell 13: filters all instances with length one. 
# These instances contain all instances with one single Form or rhythm statement.    
#

Y_copy_len_one_df = Y_copy[Y_copy["len"]==1].copy()
Y_copy_len_one_df

,ecg_id,patient_id,strat_fold,scp_codes,label,codes,len
0,1,15709.0,3,"{'NORM': 100.0, 'LVOLT': 0.0, 'SR': 0.0}","[SR, LVOLT]",[LVOLT],1
1,2,13243.0,2,"{'NORM': 80.0, 'SBRAD': 0.0}",[SBRAD],[SBRAD],1
2,3,20372.0,5,"{'NORM': 100.0, 'SR': 0.0}",[SR],[SR],1
3,4,17014.0,3,"{'NORM': 100.0, 'SR': 0.0}",[SR],[SR],1
4,5,17448.0,4,"{'NORM': 100.0, 'SR': 0.0}",[SR],[SR],1
...,...,...,...,...,...,...,...
21793,21832,7954.0,7,"{'LAFB': 100.0, 'IVCD': 100.0, 'SR': 0.0}",[SR],[SR],1
21795,21834,20703.0,4,"{'NORM': 100.0, 'ABQRS': 0.0, 'SR': 0.0}","[SR, ABQRS]",[ABQRS],1
21796,21835,19311.0,2,"{'ISCAS': 50.0, 'SR': 0.0}",[SR],[SR],1
21797,21836,8873.0,8,"{'NORM': 100.0, 'SR': 0.0}",[SR],[SR],1
21798,21837,11744.0,9,"{'NORM': 100.0, 'SR': 0.0}",[SR],[SR],1

In [29]:
#
# Cell 14: substract Y_copy_len_one_df Y_copy to get Y_all_other
#

Y_all_other = Y_copy[~Y_copy.index.isin(Y_copy_len_one_df.index)].copy()
Y_all_other

,ecg_id,patient_id,strat_fold,scp_codes,label,codes,len
16,17,13619.0,9,"{'AFLT': 100.0, 'ABQRS': 0.0, 'AFIB': 0.0}","[AFIB, ABQRS, AFLT]","[ABQRS, AFIB, AFLT]",3
19,20,13619.0,9,"{'AFLT': 100.0, 'ABQRS': 0.0}","[ABQRS, AFLT]","[ABQRS, AFLT]",2
25,26,13619.0,9,"{'NST_': 100.0, 'DIG': 100.0, 'SR': 0.0}","[DIG, SR, NST_]","[DIG, NST_]",2
27,28,13619.0,9,"{'NST_': 100.0, 'DIG': 100.0, 'SR': 0.0}","[DIG, SR, NST_]","[DIG, NST_]",2
38,39,13619.0,9,"{'IMI': 15.0, 'LNGQT': 100.0, 'NST_': 100.0, '...","[DIG, LNGQT, NST_, SR, ABQRS]","[ABQRS, DIG, LNGQT, NST_]",4
...,...,...,...,...,...,...,...
21779,21818,19204.0,10,"{'NORM': 100.0, 'ABQRS': 0.0, 'VCLVH': 0.0, 'S...","[SR, ABQRS, VCLVH]","[ABQRS, VCLVH]",2
21787,21826,9178.0,10,"{'IMI': 80.0, 'ABQRS': 0.0, 'SARRH': 0.0}","[ABQRS, SARRH]","[ABQRS, SARRH]",2
21788,21827,13862.0,5,"{'IMI': 100.0, 'ISCLA': 50.0, 'ABQRS': 0.0, 'S...","[ABQRS, SVARR]","[ABQRS, SVARR]",2
21789,21828,13862.0,5,"{'IMI': 80.0, 'ISCLA': 100.0, 'PVC': 100.0, 'A...","[SR, ABQRS, PVC]","[ABQRS, PVC]",2
21794,21833,17180.0,7,"{'NDT': 100.0, 'PVC': 100.0, 'VCLVH': 0.0, 'ST...","[STACH, VCLVH, NDT, PVC]","[NDT, PVC, STACH, VCLVH]",4

In [31]:
#
# Cell 15: convert list element of column "codes" into objects
#

Y_copy_len_one_df['codes'] = Y_copy_len_one_df['codes'].apply(lambda x: " ".join(x))
Y_copy_len_one_df

,ecg_id,patient_id,strat_fold,scp_codes,label,codes,len
0,1,15709.0,3,"{'NORM': 100.0, 'LVOLT': 0.0, 'SR': 0.0}","[SR, LVOLT]",LVOLT,1
1,2,13243.0,2,"{'NORM': 80.0, 'SBRAD': 0.0}",[SBRAD],SBRAD,1
2,3,20372.0,5,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
3,4,17014.0,3,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
4,5,17448.0,4,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
...,...,...,...,...,...,...,...
21793,21832,7954.0,7,"{'LAFB': 100.0, 'IVCD': 100.0, 'SR': 0.0}",[SR],SR,1
21795,21834,20703.0,4,"{'NORM': 100.0, 'ABQRS': 0.0, 'SR': 0.0}","[SR, ABQRS]",ABQRS,1
21796,21835,19311.0,2,"{'ISCAS': 50.0, 'SR': 0.0}",[SR],SR,1
21797,21836,8873.0,8,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
21798,21837,11744.0,9,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1

In [33]:
#
# Cell 16: filters rows from Y_copy by index of agg_df_form 
# that is, filter all form ECGs
#

Y_form_df=Y_copy_len_one_df[Y_copy_len_one_df['codes'].isin(agg_df_form.index)].copy()
Y_form_df

,ecg_id,patient_id,strat_fold,scp_codes,label,codes,len
0,1,15709.0,3,"{'NORM': 100.0, 'LVOLT': 0.0, 'SR': 0.0}","[SR, LVOLT]",LVOLT,1
7,8,11275.0,9,"{'IMI': 35.0, 'ABQRS': 0.0, 'SR': 0.0}","[SR, ABQRS]",ABQRS,1
21,22,20978.0,4,"{'NDT': 100.0, 'SR': 0.0}","[SR, NDT]",NDT,1
47,48,13672.0,9,"{'NDT': 100.0, 'SR': 0.0}","[SR, NDT]",NDT,1
53,54,16751.0,5,"{'NDT': 100.0, 'SR': 0.0}","[SR, NDT]",NDT,1
...,...,...,...,...,...,...,...
21776,21815,14433.0,3,"{'IMI': 100.0, 'AMI': 50.0, 'LAFB': 100.0, '1A...","[SR, ABQRS]",ABQRS,1
21777,21816,15103.0,3,"{'NDT': 100.0, 'SR': 0.0}","[SR, NDT]",NDT,1
21785,21824,19977.0,8,"{'AMI': 15.0, 'ABQRS': 0.0, 'SR': 0.0}","[SR, ABQRS]",ABQRS,1
21790,21829,14508.0,3,"{'NORM': 50.0, 'IRBBB': 100.0, 'ABQRS': 0.0, '...","[SR, ABQRS]",ABQRS,1
21795,21834,20703.0,4,"{'NORM': 100.0, 'ABQRS': 0.0, 'SR': 0.0}","[SR, ABQRS]",ABQRS,1

In [35]:
#
# Cell 16a: Information 
#
control = ['SR']

Y_form_df[Y_form_df.codes.isin(control)]

Empty DataFrame
Columns: [ecg_id, patient_id, strat_fold, scp_codes, label, codes, len]
Index: []

In [37]:
#
# Cell 17: filters rows from Y_copy by index of agg_df_rhythm 
# that is, filter all rhythm ECGs
#

Y_rhythm_df=Y_copy_len_one_df[Y_copy_len_one_df['codes'].isin(agg_df_rhythm.index)].copy()
Y_rhythm_df

,ecg_id,patient_id,strat_fold,scp_codes,label,codes,len
1,2,13243.0,2,"{'NORM': 80.0, 'SBRAD': 0.0}",[SBRAD],SBRAD,1
2,3,20372.0,5,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
3,4,17014.0,3,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
4,5,17448.0,4,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
5,6,19005.0,4,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
...,...,...,...,...,...,...,...
21792,21831,11905.0,9,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
21793,21832,7954.0,7,"{'LAFB': 100.0, 'IVCD': 100.0, 'SR': 0.0}",[SR],SR,1
21796,21835,19311.0,2,"{'ISCAS': 50.0, 'SR': 0.0}",[SR],SR,1
21797,21836,8873.0,8,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
21798,21837,11744.0,9,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1

In [39]:
#
# Cell 18: selects all ECGS with "SR" label resp. code  
#

Y_SR_df = Y_rhythm_df[Y_rhythm_df['codes'] == 'SR'].copy()
Y_SR_df

,ecg_id,patient_id,strat_fold,scp_codes,label,codes,len
2,3,20372.0,5,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
3,4,17014.0,3,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
4,5,17448.0,4,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
5,6,19005.0,4,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
6,7,16193.0,7,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
...,...,...,...,...,...,...,...
21792,21831,11905.0,9,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
21793,21832,7954.0,7,"{'LAFB': 100.0, 'IVCD': 100.0, 'SR': 0.0}",[SR],SR,1
21796,21835,19311.0,2,"{'ISCAS': 50.0, 'SR': 0.0}",[SR],SR,1
21797,21836,8873.0,8,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
21798,21837,11744.0,9,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1

In [41]:
#
# Cell 19: selects all Non SR rhythm labelled ECGs  
#

Y_rhythm_no_SR_df = Y_rhythm_df[~Y_rhythm_df.index.isin(Y_SR_df.index)].copy()
Y_rhythm_no_SR_df

,ecg_id,patient_id,strat_fold,scp_codes,label,codes,len
1,2,13243.0,2,"{'NORM': 80.0, 'SBRAD': 0.0}",[SBRAD],SBRAD,1
10,11,11243.0,5,"{'NORM': 80.0, 'SARRH': 0.0}",[SARRH],SARRH,1
11,12,11031.0,8,"{'NORM': 80.0, 'SBRAD': 0.0}",[SBRAD],SBRAD,1
14,15,13375.0,3,"{'NORM': 100.0, 'SARRH': 0.0}",[SARRH],SARRH,1
17,18,13619.0,9,{'AFLT': 100.0},[AFLT],AFLT,1
...,...,...,...,...,...,...,...
21753,21792,10116.0,5,"{'ISCIL': 100.0, 'RAO/RAE': 100.0, 'STACH': 0.0}",[STACH],STACH,1
21758,21797,17057.0,7,"{'LVH': 50.0, 'ISC_': 100.0, 'AFIB': 0.0}",[AFIB],AFIB,1
21764,21803,12842.0,2,"{'CRBBB': 100.0, 'SARRH': 0.0}",[SARRH],SARRH,1
21765,21804,12842.0,2,"{'CRBBB': 100.0, 'AFIB': 0.0}",[AFIB],AFIB,1
21778,21817,18354.0,9,{'PACE': 100.0},[PACE],PACE,1

In [43]:
#
# Cell 20: the instances tagged with a value 10 in the columns "strat_forld" are revied carefully 
# by a cardiologist and therefore these instances are intended for the test course.
# NOTE! these cell serves only for information about the length resp. number of rows of the corresponding df 
#

#Y_rhythm_test = Y_rhythm_no_SR_df[Y_rhythm_no_SR_df.strat_fold == 10]
#Y_rhythm_test

#Y_all_other_test = Y_all_other[Y_all_other.strat_fold == 10]
#Y_all_other_test

Y_SR_test = Y_SR_df[Y_SR_df.strat_fold == 10]
Y_SR_test

,ecg_id,patient_id,strat_fold,scp_codes,label,codes,len
8,9,18792.0,10,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
37,38,17076.0,10,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
39,40,19501.0,10,"{'NORM': 80.0, 'SR': 0.0}",[SR],SR,1
56,57,16063.0,10,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
58,59,19475.0,10,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
...,...,...,...,...,...,...,...
21124,21163,17570.0,10,"{'LMI': 15.0, 'CLBBB': 100.0, 'SR': 0.0}",[SR],SR,1
21138,21177,21738.0,10,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
21142,21181,17570.0,10,"{'CLBBB': 100.0, 'SR': 0.0}",[SR],SR,1
21405,21444,20461.0,10,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
21780,21819,9843.0,10,"{'IRBBB': 100.0, 'LAFB': 100.0, 'SR': 0.0}",[SR],SR,1

In [45]:
#
# Cell 21:  assign a unique code to all ECGs of one class (form, rhytm, all other)    
#

df_list= [[Y_form_df, 'form'], [Y_rhythm_no_SR_df, 'rhythm'], [Y_all_other, 'all_other']]

df_list
for item in df_list:
    #item[0]['codes_recover'] = item[0]['codes']
    item[0]['codes'] = item[1]

Y_rhythm_df

,ecg_id,patient_id,strat_fold,scp_codes,label,codes,len
1,2,13243.0,2,"{'NORM': 80.0, 'SBRAD': 0.0}",[SBRAD],SBRAD,1
2,3,20372.0,5,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
3,4,17014.0,3,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
4,5,17448.0,4,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
5,6,19005.0,4,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
...,...,...,...,...,...,...,...
21792,21831,11905.0,9,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
21793,21832,7954.0,7,"{'LAFB': 100.0, 'IVCD': 100.0, 'SR': 0.0}",[SR],SR,1
21796,21835,19311.0,2,"{'ISCAS': 50.0, 'SR': 0.0}",[SR],SR,1
21797,21836,8873.0,8,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
21798,21837,11744.0,9,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1

In [51]:
#
# Cell 22: splits the test instances from the different classes by the strat_fold value 10.
#

dfs = {
    'form': Y_form_df,
    'rhythm_no_SR': Y_rhythm_no_SR_df,
    'all_other': Y_all_other,
    'SR': Y_SR_df
}

test_dfs = {name: df[df['strat_fold'] == 10].copy() for name, df in dfs.items()}
print('len test_dfs[SR]: ', len(test_dfs['SR']))
print('len test_dfs[form]: ', len(test_dfs['form']))
print('len test_dfs[rhythm_no_SR]: ', len(test_dfs['rhythm_no_SR']))
print('len test_dfs[all_other]: ', len(test_dfs['all_other']))

len test_dfs[SR]:  1013
len test_dfs[form]:  517
len test_dfs[rhythm_no_SR]:  228
len test_dfs[all_other]:  368

In [53]:
test_dfs['all_other']

,ecg_id,patient_id,strat_fold,scp_codes,label,codes,len
232,240,9601.0,10,"{'IMI': 50.0, 'ABQRS': 0.0, 'SBRAD': 0.0}","[ABQRS, SBRAD]",all_other,2
263,271,449.0,10,"{'ASMI': 100.0, 'LVH': 100.0, 'ISC_': 100.0, '...","[STD_, SR, PAC]",all_other,2
266,274,5662.0,10,"{'ASMI': 100.0, 'LVH': 100.0, 'ISC_': 100.0, '...","[STD_, SR, INVT, VCLVH]",all_other,3
310,318,2034.0,10,"{'NDT': 100.0, 'DIG': 80.0, 'STD_': 0.0, 'AFIB...","[STD_, DIG, AFIB, NDT]",all_other,4
328,336,449.0,10,"{'LVH': 100.0, 'ISC_': 100.0, 'PVC': 100.0, 'N...","[AFLT, NST_, SVTAC, PVC]",all_other,4
...,...,...,...,...,...,...,...
21634,21673,12998.0,10,"{'ISCAL': 50.0, 'LVH': 15.0, 'VCLVH': 0.0, 'AF...","[AFIB, VCLVH]",all_other,2
21757,21796,17746.0,10,"{'IMI': 50.0, 'ASMI': 50.0, 'IRBBB': 100.0, 'A...","[AFIB, ABQRS]",all_other,2
21773,21812,20789.0,10,"{'CRBBB': 100.0, 'LAFB': 100.0, '1AVB': 100.0,...","[ABQRS, SVARR]",all_other,2
21779,21818,19204.0,10,"{'NORM': 100.0, 'ABQRS': 0.0, 'VCLVH': 0.0, 'S...","[SR, ABQRS, VCLVH]",all_other,2
21787,21826,9178.0,10,"{'IMI': 80.0, 'ABQRS': 0.0, 'SARRH': 0.0}","[ABQRS, SARRH]",all_other,2

In [55]:
#
# Cell 23: substracts for all classes the corresponding test instances from the sets.
# Generates the dictionary "residue_dfs" with all the residue df of the individual classes  
#

dfs = {
    'form_res': [Y_form_df, test_dfs['form']],
    'rhythm_no_SR_res': [Y_rhythm_no_SR_df, test_dfs['rhythm_no_SR']],
    'all_other_res': [Y_all_other, test_dfs['all_other']],
    'SR_res': [Y_SR_df, test_dfs['SR']]
}


residue_dfs = {name: df[0][~df[0].index.isin(df[1].index)].copy() for name, df in dfs.items()}

residue_dfs['SR_res']


print('len residue_dfs[SR_res]: ', len(residue_dfs['SR_res']))
print('len residue_dfs[form_res]: ', len(residue_dfs['form_res']))
print('len residue_dfs[rhythm_no_SR_res]: ', len(residue_dfs['rhythm_no_SR_res']))
print('len residue_dfs[all_other_res]: ', len(residue_dfs['all_other_res']))

len test_dfs[SR_res]:  9112
len test_dfs[form_res]:  4704
len test_dfs[rhythm_no_SR_res]:  1930
len test_dfs[all_other_res]:  3425

In [62]:
residue_dfs['all_other_res']

,ecg_id,patient_id,strat_fold,scp_codes,label,codes,len
16,17,13619.0,9,"{'AFLT': 100.0, 'ABQRS': 0.0, 'AFIB': 0.0}","[ABQRS, AFLT, AFIB]","[ABQRS, AFIB, AFLT]",3
19,20,13619.0,9,"{'AFLT': 100.0, 'ABQRS': 0.0}","[ABQRS, AFLT]","[ABQRS, AFLT]",2
25,26,13619.0,9,"{'NST_': 100.0, 'DIG': 100.0, 'SR': 0.0}","[DIG, NST_, SR]","[DIG, NST_]",2
27,28,13619.0,9,"{'NST_': 100.0, 'DIG': 100.0, 'SR': 0.0}","[DIG, NST_, SR]","[DIG, NST_]",2
38,39,13619.0,9,"{'IMI': 15.0, 'LNGQT': 100.0, 'NST_': 100.0, '...","[NST_, LNGQT, ABQRS, DIG, SR]","[ABQRS, DIG, LNGQT, NST_]",4
...,...,...,...,...,...,...,...
21745,21784,12488.0,1,"{'IMI': 100.0, 'NDT': 100.0, '1AVB': 100.0, 'A...","[ABQRS, NDT, SR]","[ABQRS, NDT]",2
21755,21794,12543.0,1,"{'NDT': 100.0, 'AFIB': 0.0}","[AFIB, NDT]","[AFIB, NDT]",2
21788,21827,13862.0,5,"{'IMI': 100.0, 'ISCLA': 50.0, 'ABQRS': 0.0, 'S...","[ABQRS, SVARR]","[ABQRS, SVARR]",2
21789,21828,13862.0,5,"{'IMI': 80.0, 'ISCLA': 100.0, 'PVC': 100.0, 'A...","[PVC, ABQRS, SR]","[ABQRS, PVC]",2
21794,21833,17180.0,7,"{'NDT': 100.0, 'PVC': 100.0, 'VCLVH': 0.0, 'ST...","[STACH, PVC, NDT, VCLVH]","[NDT, PVC, STACH, VCLVH]",4

In [124]:
#
# Cell 24: splits the df in the dictionary "residue_dfs" in training and validation sets.
#

dfs = {
    'form_training': residue_dfs['form_res'],
    'rhythm_training': residue_dfs['rhythm_no_SR_res'],
    'all_other_training': residue_dfs['all_other_res'],
    'SR_training': residue_dfs['SR_res']
}

training_dfs = {
    name: df.sample(frac=0.75, random_state=7).copy()
    for name, df in dfs.items()
}

print('len training_dfs[SR_training]: ', len(training_dfs['SR_training']))
print('len training_dfs[form_training]: ', len(training_dfs['form_training']))
print('len training_dfs[rhythm_training]: ', len(training_dfs['rhythm_training']))
print('len training_dfs[all_other_training]: ', len(training_dfs['all_other_training']), '\n')


validation_dfs = {
    name.replace('_training', '_validation'): df.drop(training_dfs[name].index).copy()
    for name, df in dfs.items()
}

print('len validation_dfs[SR_validation]: ', len(validation_dfs['SR_validation']))
print('len validation_dfs[form_validation]: ', len(validation_dfs['form_validation']))
print('len validation_dfs[rhythm_validation]: ', len(validation_dfs['rhythm_validation']))
print('len validation_dfs[all_other_validation]: ', len(validation_dfs['all_other_validation']))

display(training_dfs['SR_training'][0:5]) 
display(validation_dfs['SR_validation'][0:5])

len training_dfs[SR_training]:  6834
len training_dfs[form_training]:  3528
len training_dfs[rhythm_training]:  1448
len training_dfs[all_other_training]:  2569

len validation_dfs[SR_validation]:  2278
len validation_dfs[form_validation]:  1176
len validation_dfs[rhythm_validation]:  482
len validation_dfs[all_other_validation]:  856

,ecg_id,patient_id,strat_fold,scp_codes,label,codes,len
5797,5818,20223.0,4,"{'LMI': 15.0, 'SR': 0.0}",[SR],SR,1
10032,10059,1314.0,4,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
3224,3239,8716.0,4,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
9822,9848,614.0,5,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
19150,19189,11354.0,6,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1

,ecg_id,patient_id,strat_fold,scp_codes,label,codes,len
3,4,17014.0,3,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
5,6,19005.0,4,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
13,14,12925.0,7,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
28,29,14340.0,4,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
32,33,20527.0,3,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1

In [126]:
#
# Cell 25: count the number of instances splits the df in the dictionary "residue_dfs" in training and validation sets.
#

dfs_all= {1: test_dfs,
          2: training_dfs,
          3: validation_dfs
         }

summation=sum(df.shape[0] for df in dfs_all.values() for df in df.values())
print('Total sum of all instances in the different sets: ',summation)

Total sum of all instances in the different sets:  21297

In [128]:
#
# Cell 26:
#

train_df = pd.concat(training_dfs.values(), axis=0).sample(frac=1, random_state=7)
val_df   = pd.concat(validation_dfs.values(), axis=0).sample(frac=1, random_state=7)
test_df  = pd.concat(test_dfs.values(), axis=0).sample(frac=1, random_state=7)

In [109]:
test_df

,ecg_id,patient_id,strat_fold,scp_codes,label,codes,len
11618,11645,8388.0,10,"{'ASMI': 15.0, 'SR': 0.0}",[SR],SR,1
11391,11418,13679.0,10,"{'CLBBB': 100.0, 'STACH': 0.0, 'BIGU': 0.0}","[STACH, BIGU]",all_other,2
4342,4362,5313.0,10,"{'IMI': 15.0, 'SR': 0.0}",[SR],SR,1
17921,17959,1494.0,10,"{'ISCAS': 100.0, 'INVT': 0.0, 'STD_': 0.0, 'SA...","[STD_, SARRH, INVT]",all_other,3
1626,1639,3283.0,10,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
...,...,...,...,...,...,...,...
2272,2285,2208.0,10,"{'LAFB': 80.0, 'SR': 0.0}",[SR],SR,1
1413,1426,16997.0,10,"{'LVH': 100.0, 'ISCIN': 100.0, 'PVC': 100.0}",[PVC],form,1
4005,4025,648.0,10,"{'NORM': 80.0, 'PAC': 0.0, 'PVC': 0.0, 'STACH'...","[STACH, PAC, PVC]",all_other,3
19566,19605,14515.0,10,"{'NORM': 100.0, 'SR': 0.0}",[SR],SR,1
19178,19217,18359.0,10,"{'NORM': 100.0, 'SBRAD': 0.0}",[SBRAD],rhythm,1

In [130]:
#
# Cell 27: puts dataframes into dictionary
#

Y_final_dfs = {'train_df' : train_df, 'val_df': val_df, 'test_df' : test_df}

## Following cell (37 to 42) are for preparing X data without augmentation

In [113]:
#
#Cell 28: loads original X values (no augmentation) 
#

from pathlib import Path

X_directory_path = Path("D:/ECG/X_zero")
X = np.load(X_directory_path/'X_float32.npy', mmap_mode='r')

In [132]:
#
# Cell 29:
#

X_train = X[train_df.index.tolist(), :, :]
X_val   = X[val_df.index.tolist(), :, :]
X_test  = X[test_df.index.tolist(), :, :]

In [162]:
X_test.shape

(2126, 1000, 12)

In [118]:
# Cell 30: creates a folder for data storage.

from pathlib import Path

# Specify the directory name
directory_path = Path("D:/ECG/XY_diff_class_2_new")

# Create the directory
try:
    directory_path.mkdir()
    print(f"Directory '{directory_path}' created successfully.")
except FileExistsError:
    print(f"Directory '{directory_path}' already exists.")
except PermissionError:
    print(f"Permission denied: Unable to create '{directory_path}'.")
except Exception as e:
    print(f"An error occurred: {e}")

Directory 'D:\ECG\XY_diff_class_2_new' already exists.

In [134]:
#
# Cell 31: stores the X data (numpy arrays) to archive in the created folder    
#

np.savez(directory_path/'X_np_arrays_3.npz', a = X_train, b = X_val, c = X_test)

In [136]:
#
# Cell 32: Saves Y_final_dfs and X_final_dfs
#

import pickle

with open(directory_path/'Y_data_3.pkl', 'wb') as f:  # open a text file
    pickle.dump(Y_final_dfs, f) # serialize the list
    f.close()

#with open(directory_path/'X_data.pkl', 'wb') as f:  # open a text file
#    pickle.dump(X_final_dfs, f) # serialize the list
#    f.close()

## The following cells must be executed if one wants to use the augmented datasets of X

In [82]:
#
# Cell 33: path to read input data
#

X_directory_path = Path("D:/ECG/X_augmented_1000") # chose the right path beforhand
X = np.load(X_directory_path/'X_augmented.npz.npy', mmap_mode='r')

In [85]:
#
# Cell 34: divides X values in training-, validation- and test data.
#

X_train = X[train_df.index.tolist(), :, :]
X_val   = X[val_df.index.tolist(), :, :]
X_test  = X[test_df.index.tolist(), :, :]

In [89]:
#
# Cell 35: creates a folder for data storage.
#

from pathlib import Path


# Specify the directory name
directory_path = Path("D:/ECG/XY_diff_class_2_aug_1000") # chose the right path beforhand

# Create the directory
try:
    directory_path.mkdir()
    print(f"Directory '{directory_path}' created successfully.")
except FileExistsError:
    print(f"Directory '{directory_path}' already exists.")
except PermissionError:
    print(f"Permission denied: Unable to create '{directory_path}'.")
except Exception as e:
    print(f"An error occurred: {e}")

Directory 'D:\ECG\XY_diff_class_2_aug_1000' created successfully.

In [92]:
#
# Cell 36: stores the X data (numpy arrays) to archive in the created folder    
#

np.savez(directory_path/'X_np_arrays.npz', a = X_train, b = X_val, c = X_test)

In [99]:
#
# Cell 37: Saves Y_final_dfs and X_final_dfs
#

import pickle

with open(directory_path/'Y_data.pkl', 'wb') as f:  # open a text file
    pickle.dump(Y_final_dfs, f) # serialize the list
    f.close()

#with open(directory_path/'X_data.pkl', 'wb') as f:  # open a text file
#    pickle.dump(X_final_dfs, f) # serialize the list
#    f.close()